### ISSUE TITLE
Независимо от начальной вершину на след. шаге рассматриваем вершину 1

### ISSUE THREAD

**Issue by sholokhova** [lyushninaelena/prim_java_2016#10]
Видимо из-за добавления каждый раз
Edge e = new Edge(zero, zero, 0);
в методе Graph.clear() каждый раз второй по счету рассматриваем вершину 1, независимо от того, с какой вершины начали

**Comment by lyushninaelena** [comment]
Не совсем поняла вопроса

**Comment by lyushninaelena** [comment]
Не совсем поняла вопрос

**Comment by sholokhova** [comment]
В примере, который лежит в репозитории, если выбрать в качестве начальной вершины, вершину 5, то получаем

Вершина 5 добавлена в МОД
Далее рассмотрим вершину 1

Пропуская вершину 4

**Comment by lyushninaelena** [comment]
Это происходило из-за того что граф считывался как ориентированный. Исправила
