### ISSUE TITLE
Индесация в массиве

### ISSUE THREAD

**Issue by sholokhova** [lyushninaelena/prim_java_2016#11]
Algorithm.executeStepAlgorithm
Видимо, все таки for (byte i = 0; i < numVertices; ++i)  
v = 1;
            dist = MAX_INT;
            for (byte i = 1; i <= numVertices; ++i) {
                if (!intree[i] && dist > distance[i]) {
                    dist = distance[i];
                    v = i;
                }
            }

**Comment by lyushninaelena** [comment]
Данные в массив записываются именно с 1 и до количества вершин включительно (для того чтобы было проще работать с вершинами)
