### ISSUE TITLE
[Code review] Refactoring

### ISSUE THREAD

**Issue by sholokhova** [lyushninaelena/prim_java_2016#9]
1. [Graph.java#L98](https://github.com/lyushninaelena/prim_java_2016/blob/master/src/Graph.java#L98) Видимо, можно сразу проверять edges[_x], а не искать в цикле
2. [Graph.java#L98](https://github.com/lyushninaelena/prim_java_2016/blob/master/src/Graph.java#L98) Можно всегда добавлять в голову списка, и не хранить last
3. [Algorithm.java#L16](https://github.com/lyushninaelena/prim_java_2016/blob/master/src/Algorithm.java#L16) Есть константа Integer.MAX_VALUE
4. Возможно, стоило бы не ограничивать количество вершин в графе константой MAX_V, а создавать граф во время считывания и файла, передавая количество вершин в графе в конструктор Graph
5. [Algorithm.java#L69](https://github.com/lyushninaelena/prim_java_2016/blob/master/src/Algorithm.java#L69)
   Возможно, корнструкции вида
   byte vertex_y;
   temp = scan.nextByte();
   if (temp <= 0) throw new IllegalArgumentException();
   else
   vertex_y = temp;
   читаются легче в виде:
   byte vertex_y = scan.nextByte();
   if (vertex_y <= 0) throw new IllegalArgumentException();

**Comment by lyushninaelena** [comment]
1.  Я решила, что 2 миллиарда слишком много для веса ребра и решила взять 1000
2.  Из-за такого каким образом мы рисуем граф, мы не можем добавить в него большое количество вершин, поэтому мы вынуждены ограничивать их количество.

Остальное исправила
